Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.define "app" do |app| 
   app.vm.box = "ubuntu/xenial64"
   app.vm.synced_folder ".", "/home/vagrant/Multi_Machine_env" 
   app.vm.network "private_network", ip: "192.168.56.2"
   app.vm.provision "shell", path: "./provision.sh"
  end
 
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.network "private_network", ip:"192.168.56.4"
    db.vm.synced_folder ".", "/home/vagrant/Multi_Machine_env"
    db.vm.provision "shell", path: "./provision_db.sh"
    Eco'export DB_HOST="mongodb://192.168.10.150:27017/posts"
  end
end
